### ISSUE TITLE
Where is FFT.h?

### ISSUE THREAD

**Issue by nonzhe** [yliniemi/bluetooth-spectrum-analyzer#1]
Thank you for sharing.But where is FFT.h?

**Comment by yliniemi** [comment]
I thought I included the link to the fft github repository but it turns out I didn't. I don't know if I can include the source code of the fft library on my own repository and do it legally. My program is licenced with agpl 3.0 and his library has a different licence.

Anyway. Here is the link to his library.
https://github.com/fakufaku/esp32-fft

**Comment by nonzhe** [comment]
Thanks.
And the "BluetoothA2DPSink" library  from  pschatzmann/ESP32-A2DP?

**Comment by yliniemi** [comment]
I just updated the program to my current testing version. Almost current. I've heavily modified the led library to get the fps from 70 to 115 but this version uses the original version of the library. I'll put a pull request for my modifications after I do more testing on it in a couple of weeks.

Here are links to all he libraries I use:
https://github.com/hpwit/I2SClocklessLedDriver                // I use a heavily modified version of this library. Will be putting a pull request on his github repo after I've done more testing.
https://github.com/fakufaku/esp32-fft                         // This is the fastest FFT library I could find. Analyzing 4096 samples takes 5 milliseconds.
https://github.com/pschatzmann/ESP32-A2DP

Feel free to ask me if the program still doesn't compile. There might be something I've missed.

**Comment by chinasy519** [comment]
你好？我是电子爱好者我不会编程，在YouTube上看到你的视频，非常喜欢 能把FFT.h这个文件或者把这个程序的.bin文件发给我吗。chinasy519@gmail.com
